# Example YAML for the bare minimum of required elements
swagger: '2.0'


# This is you document information section
info:
  version: "0.0.1"
  title: PickupSports
  description: Schedule your sports, PUGs, and scrims smarter with PickupSports!

# Describe your paths here
paths:

  # This is a path endpoint
  /events:

    # This is an HTTP operation
    post:

      # Describe this verb here. Note: you can use markdown
      description: |
        Adds/updates information about an event. 


      # This is array of this verbs parameters:
      parameters:

        # A parameter that is in query and required
        - name: size
          in: query
          description: Size of array.
          required: true
          type: number
          format: double
        - name: sport
          in: query
          description: Name of the sport.
          required: true
          type: string
        - name: attendance
          in: query
          description: Number of people currently commited to attending.
          required: true
          type: number
          format: integer
        - name: skill_level
          in: query
          description: Skill level of event (beginner, advanced, expert).
          required: true
          type: number
          format: integer
        - name: equipment
          in: query
          description: Equipment needed for event.
          required: true
          type: string
        - name: location
          in: query
          description: Address or location of event.
          required: true
          type: string


      # Expected responses for this verb:
      responses:

        # Response code
        200:
          description: Successful response with a body that is a list of json objects matching the above description. 
        400: 
          description: There is an error with the request.
        500: 
          description: Server error. 

          # A schema describes your response object shape.
          # Use JSON Schema format
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean
